# NOTE: This name appears in GitHub's Checks API and in workflow's status badge.
name: ci-test

# Trigger the workflow when:
on:
  # A push occurs to one of the matched branches.
  push:
    branches:
      - main
      - stable/*
  # Or when a pull request event occurs for a pull request against one of the
  # matched branches.
  pull_request:
    branches:
      - main
      - stable/*

# Cancel in-progress jobs on same branch.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-go:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_HOST: 127.0.0.1
          POSTGRES_PORT: 5432
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
    env:
      OASIS_CORE_VERSION: "22.1.8"
      OASIS_NODE: ${{ github.workspace }}/oasis_core/oasis-node
      OASIS_NET_RUNNER: ${{ github.workspace }}/oasis_core/oasis-net-runner
      EMERALD_PARATIME_VERSION: 9.0.1
      GATEWAY__CHAIN_ID: 42262
      EMERALD_PARATIME: ${{ github.workspace }}/oasis_core/emerald-paratime
      OASIS_NODE_DATADIR: /tmp/eth-runtime-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3.3.1
        with:
          go-version: "1.17"

      - name: Install prerequisites
        run: |
          sudo apt update && sudo apt install bubblewrap unzip -y
          wget "https://github.com/oasisprotocol/oasis-core/releases/download/v${OASIS_CORE_VERSION}/oasis_core_${OASIS_CORE_VERSION}_linux_amd64.tar.gz"
          tar xfvz "oasis_core_${OASIS_CORE_VERSION}_linux_amd64.tar.gz"
          mkdir -p "$(dirname ${OASIS_NODE})"
          mv "oasis_core_${OASIS_CORE_VERSION}_linux_amd64/oasis-node" "${OASIS_NODE}"
          mkdir -p "$(dirname ${OASIS_NET_RUNNER})"
          mv "oasis_core_${OASIS_CORE_VERSION}_linux_amd64/oasis-net-runner" "${OASIS_NET_RUNNER}"
          mkdir -p "$(dirname ${EMERALD_PARATIME})"
          wget "https://github.com/oasisprotocol/emerald-paratime/releases/download/v${EMERALD_PARATIME_VERSION}/emerald-paratime.orc" -O "${EMERALD_PARATIME}.orc"
          unzip "${EMERALD_PARATIME}.orc"
          mv runtime.elf "${EMERALD_PARATIME}"
          chmod a+x "${EMERALD_PARATIME}"

      - name: Spinup oasis-node
        run: tests/tools/spinup-oasis-stack.sh > /dev/null &

      - name: Unit tests with coverage
        run: go test -race -coverpkg=./... -coverprofile=coverage.txt -covermode=atomic -v ./...

      - name: Shutdown oasis-node
        run: killall oasis-node
        if: always()

      - name: Upload oasis-node logs artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: oasis-node-logs
          path: ${{ env.OASIS_NODE_DATADIR }}/**/*.log

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v3.1.0

  test-go-c10l:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_HOST: 127.0.0.1
          POSTGRES_PORT: 5432
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
    env:
      OASIS_CORE_VERSION: "22.1.9"
      OASIS_NODE: ${{ github.workspace }}/oasis_core/oasis-node
      OASIS_NET_RUNNER: ${{ github.workspace }}/oasis_core/oasis-net-runner
      EMERALD_PARATIME_VERSION: 0.1.3-testnet
      GATEWAY__CHAIN_ID: 23295
      GATEWAY__OASIS_RPCS: true
      EMERALD_PARATIME: ${{ github.workspace }}/oasis_core/sapphire-paratime
      KEYMANAGER_ARTIFACT_URL: https://buildkite.com/organizations/oasisprotocol/pipelines/oasis-core-ci/builds/9098/jobs/01824af5-09bf-4ca0-a645-f63675e87f49/artifacts/01824af8-a4a1-4f17-a598-3be41a165b15 # Find this at https://buildkite.com/oasisprotocol/oasis-core-ci/builds?branch=stable%2F<...> under "Build runtimes".
      KEYMANAGER_BINARY: ${{ github.workspace }}/oasis_core/simple-keymanager
      OASIS_NODE_DATADIR: /tmp/eth-runtime-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3.3.1
        with:
          go-version: "1.17"

      - name: Install prerequisites
        run: |
          sudo apt update && sudo apt install bubblewrap unzip -y
          # oasis-core
          wget "https://github.com/oasisprotocol/oasis-core/releases/download/v${OASIS_CORE_VERSION}/oasis_core_${OASIS_CORE_VERSION}_linux_amd64.tar.gz"
          tar xfvz "oasis_core_${OASIS_CORE_VERSION}_linux_amd64.tar.gz"
          mkdir -p "$(dirname ${OASIS_NODE})"
          mv "oasis_core_${OASIS_CORE_VERSION}_linux_amd64/oasis-node" "${OASIS_NODE}"
          mkdir -p "$(dirname ${OASIS_NET_RUNNER})"
          mv "oasis_core_${OASIS_CORE_VERSION}_linux_amd64/oasis-net-runner" "${OASIS_NET_RUNNER}"
          mkdir -p "$(dirname ${EMERALD_PARATIME})"
          # sapphire-paratime
          wget "https://github.com/oasisprotocol/sapphire-paratime/releases/download/v${EMERALD_PARATIME_VERSION}/insecure-debug-sapphire-paratime.orc" -O "${EMERALD_PARATIME}.orc"
          unzip "${EMERALD_PARATIME}.orc"
          mv runtime.elf "${EMERALD_PARATIME}"
          chmod a+x "${EMERALD_PARATIME}"
          # simple-keymanager
          wget "${KEYMANAGER_ARTIFACT_URL}" -O "${KEYMANAGER_BINARY}"

      - name: Spinup oasis-node
        run: tests/tools/spinup-oasis-stack.sh > /dev/null &

      - name: Unit tests with coverage
        run: go test -race -coverpkg=./... -coverprofile=coverage.txt -covermode=atomic -v ./...

      - name: Shutdown oasis-node
        run: killall oasis-node
        if: always()

      - name: Upload oasis-node logs artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: oasis-node-logs-c10l
          path: ${{ env.OASIS_NODE_DATADIR }}/**/*.log

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v3.1.0
